import time
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.select import Select
from selenium import webdriver
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.maximize_window()
driver.get("https://demo.us.espocrm.com/")
time.sleep(5)
language = driver.find_element_by_id("field-language")
Select_language = Select(language)
Select_language.select_by_value('en_US')
login = driver.find_element_by_id("btn-login")
login.click()
time.sleep(7)

activities = driver.find_element_by_id('nav-tab-group-group-8')
activities.click()
Tasks = driver.find_element_by_link_text('Tasks')
Tasks.click()
time.sleep(7)
all = driver.find_element_by_class_name('filters-label')
all.click()
only_my = driver.find_element_by_css_selector('li.checkbox:nth-child(11)')
only_my.click()
time.sleep(3)
all_select = driver.find_element_by_class_name('select-all')
all_select.click()
time.sleep(6)
actions = driver.find_element_by_class_name('actions').click()
Mass_Update = driver.find_element_by_css_selector('.dropdown-menu.actions-menu > :nth-child(3)').click()
time.sleep(6)
update = driver.find_element_by_css_selector('[data-name="update"]')
update = update.get_attribute('disabled')
if update is not None:
    print ('blocked')
else:
    print('no blocked')
x = driver.find_element_by_css_selector('[data-dismiss="modal"]')
x.click()
Create_task = driver.find_element_by_link_text('Create Task')
Create_task.click()
time.sleep(20)
Name = driver.find_element_by_xpath('//input[@data-name="name"]')
Name.send_keys("Test")
Status = driver.find_element_by_css_selector('.col-sm-6:nth-child(1) select')
Status = Status.get_attribute('value')
if Status == 'Not Started':
    print(Status)
else:
    print('No')
save = driver.find_element_by_css_selector(".btn-xs-wide:nth-child(1)")
save.click()
time.sleep(4)
driver.find_element_by_css_selector(".breadcrumb-item .action").click()
time.sleep(4)
driver.find_element_by_css_selector(".list-row:nth-child(1) .record-checkbox-container").click()
time.sleep(4)
actions = driver.find_element_by_class_name('actions').click()
time.sleep(4)
Mass_Update = driver.find_element_by_css_selector('.dropdown-menu.actions-menu > :nth-child(1)').click()
time.sleep(6)
driver.quit()